table 'Customer Lookup'
	excludeFromModelRefresh
	lineageTag: a461d2eb-d4a6-452d-a3f2-25e25c96c729

	measure 'Full Name (Customer Detail)' =
			
			IF(
			    HASONEVALUE(
			        'Customer Lookup'[CustomerKey]
			    ),
			    MAX(
			        'Customer Lookup'[Full Name]
			    ),
			    "Multiple Customers"
			)
		lineageTag: ff94c86e-ba91-4e8d-9068-fb5430dcbd9d

	column CustomerKey
		dataType: int64
		isKey
		formatString: 0
		lineageTag: 3c4681ec-c209-484f-bb5e-4ff6a4df8541
		summarizeBy: none
		sourceColumn: CustomerKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Prefix
		dataType: string
		lineageTag: 73af1743-7e36-4634-8afa-f36c75a20e3f
		summarizeBy: none
		sourceColumn: Prefix

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		lineageTag: e8e7bff1-7fa5-4309-a5f7-449eeed59391
		summarizeBy: none
		sourceColumn: FirstName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		lineageTag: de44762c-e276-4061-9398-bb5867911863
		summarizeBy: none
		sourceColumn: LastName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column BirthDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4643fded-3fbe-4604-aa1f-b9838fed8643
		summarizeBy: none
		sourceColumn: BirthDate

		variation Variation
			isDefault
			relationship: 6f0a1bc7-8486-45a5-9b95-097b79569da8
			defaultHierarchy: LocalDateTable_43711212-8f6c-4f58-b18b-dca10a6a596c.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column MaritalStatus
		dataType: string
		lineageTag: 77de9b5a-e4d0-4586-8395-f473370b0f0d
		summarizeBy: none
		sourceColumn: MaritalStatus

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: 5633e9e7-92b7-4384-b7d6-279618923388
		summarizeBy: none
		sourceColumn: Gender

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column EmailAddress
		dataType: string
		lineageTag: ba54b281-e7e6-477a-acd7-cf796757e6c7
		summarizeBy: none
		sourceColumn: EmailAddress

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AnnualIncome
		dataType: int64
		formatString: 0
		lineageTag: 4ae6305a-9cb4-4efd-8c49-95f9b3c07396
		summarizeBy: sum
		sourceColumn: AnnualIncome

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column TotalChildren
		dataType: int64
		formatString: 0
		lineageTag: 4a4b67df-4756-420d-8658-3d1cbd13362e
		summarizeBy: sum
		sourceColumn: TotalChildren

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column EducationLevel
		dataType: string
		lineageTag: 8eababb1-5f66-4d29-af34-9b568d2de758
		summarizeBy: none
		sourceColumn: EducationLevel

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Occupation
		dataType: string
		lineageTag: c9634db4-6506-4a33-acf5-6cc1a4353ae8
		summarizeBy: none
		sourceColumn: Occupation

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column HomeOwner
		dataType: string
		lineageTag: f41668e8-8c62-4e2f-81ef-d6790a68c2fd
		summarizeBy: none
		sourceColumn: HomeOwner

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Full Name'
		dataType: string
		lineageTag: fbceb02f-7cee-4863-9e1a-6387247f4494
		summarizeBy: none
		sourceColumn: Full Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Domain Name'
		dataType: string
		lineageTag: ba09ba86-3217-4bd3-823b-415b71ecec38
		summarizeBy: none
		sourceColumn: Domain Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Parent =
			
			IF(
			    'Customer Lookup'[TotalChildren] > 0,
			    "Yes",
			    "No"
			)
		dataType: string
		lineageTag: 98eea16c-9ce2-4a05-adc1-a05ddf5f1606
		summarizeBy: none
		isDataTypeInferred

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Customer Priority' =
			
			IF(
			    'Customer Lookup'[AnnualIncome] > 100000 &&
			    'Customer Lookup'[Parent] = "Yes",
			    "Priority",
			    "Standard"
			)
		dataType: string
		lineageTag: 6e44277e-e618-4fe6-b374-849269d02da0
		summarizeBy: none
		isDataTypeInferred

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Income Level' =
			
			IF('Customer Lookup'[AnnualIncome] >= 150000, "Very High",
			IF('Customer Lookup'[AnnualIncome] >= 100000, "High",
			IF('Customer Lookup'[AnnualIncome] >= 50000, "Average",
			"Low")))
		dataType: string
		lineageTag: ca882298-a976-4c26-9cfe-05631a0f3910
		summarizeBy: none
		isDataTypeInferred

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Education Category' =
			
			SWITCH('Customer Lookup'[EducationLevel],
			"High School", "High School",
			"Partial High School", "High School",
			"Bachelors", "Undergrad",
			"Partial College", "Undergrad",
			"Graduate Degree", "Graduate")
		dataType: string
		lineageTag: 1d04de86-1ce2-44cc-bd47-dfd607e221f6
		summarizeBy: none
		isDataTypeInferred

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Customer Full Name (CC)' =
			
			'Customer Lookup'[Prefix] & " " & 'Customer Lookup'[FirstName] & " " & 'Customer Lookup'[LastName]
		dataType: string
		lineageTag: 3e64c53f-8323-450d-9a8c-e6760e7fc032
		summarizeBy: none
		isDataTypeInferred

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Birth Year' =
			
			YEAR('Customer Lookup'[BirthDate])
		dataType: int64
		formatString: 0
		lineageTag: fb5f5e28-31f0-4572-92dd-0b0621e1f6c1
		summarizeBy: sum
		isDataTypeInferred

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Customer Lookup' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\DELL\OneDrive\Desktop\Anisha Pogade\AdventureWorks+Raw+Data\AdventureWorks Raw Data\AdventureWorks Customer Lookup.csv"),[Delimiter=",", Columns=13, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"CustomerKey", Int64.Type}, {"Prefix", type text}, {"FirstName", type text}, {"LastName", type text}, {"BirthDate", type date}, {"MaritalStatus", type text}, {"Gender", type text}, {"EmailAddress", type text}, {"AnnualIncome", Int64.Type}, {"TotalChildren", Int64.Type}, {"EducationLevel", type text}, {"Occupation", type text}, {"HomeOwner", type text}}),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Changed Type", {"CustomerKey"}),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Errors", each [CustomerKey] <> null and [CustomerKey] <> ""),
				    #"Capitalized Each Word" = Table.TransformColumns(#"Filtered Rows",{{"Prefix", Text.Proper, type text}, {"FirstName", Text.Proper, type text}, {"LastName", Text.Proper, type text}}),
				    #"Inserted Full Name Column" = Table.AddColumn(#"Capitalized Each Word", "Full Name", each Text.Combine({[Prefix], [FirstName], [LastName]}, " "), type text),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Inserted Full Name Column", "EmailAddress", "EmailAddress - Copy"),
				    #"Renamed Columns" = Table.RenameColumns(#"Duplicated Column",{{"EmailAddress - Copy", "Domain Name"}}),
				    #"Extracted Text After Delimiter" = Table.TransformColumns(#"Renamed Columns", {{"Domain Name", each Text.AfterDelimiter(_, "@"), type text}}),
				    #"Extracted Text Before Delimiter" = Table.TransformColumns(#"Extracted Text After Delimiter", {{"Domain Name", each Text.BeforeDelimiter(_, "."), type text}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Extracted Text Before Delimiter","-"," ",Replacer.ReplaceText,{"Domain Name"}),
				    #"Capitalized Each Word1" = Table.TransformColumns(#"Replaced Value",{{"Domain Name", Text.Proper, type text}})
				in
				    #"Capitalized Each Word1"

	annotation PBI_ResultType = Table

