table 'Product Categories Lookup'
	excludeFromModelRefresh
	lineageTag: 3836d4f6-02e3-4e67-824e-5ab18522ee36

	column ProductCategoryKey
		dataType: int64
		isKey
		formatString: 0
		lineageTag: e2ed080c-0a0e-49d1-a230-9af794d5b145
		summarizeBy: none
		sourceColumn: ProductCategoryKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CategoryName
		dataType: string
		lineageTag: f2fb47a6-5fb1-4c43-9ae3-fbba47bed315
		summarizeBy: none
		sourceColumn: CategoryName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Product Categories Lookup' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\DELL\OneDrive\Desktop\Anisha Pogade\AdventureWorks+Raw+Data\AdventureWorks Raw Data\AdventureWorks Product Categories Lookup.csv"),[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ProductCategoryKey", Int64.Type}, {"CategoryName", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

